"""empty message

Revision ID: 3c0bbd01f741
Revises: ef7c1b8061fc
Create Date: 2023-02-26 00:42:18.156621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0bbd01f741'
down_revision = 'ef7c1b8061fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'auth_user_groups', 'auth_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'auth_user_groups', 'auth_group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'link_connection', 'link', ['id_link'], ['id'])
    op.create_foreign_key(None, 'link_connection', 'link', ['id_href'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link_connection', type_='foreignkey')
    op.drop_constraint(None, 'link_connection', type_='foreignkey')
    op.drop_constraint(None, 'auth_user_groups', type_='foreignkey')
    op.drop_constraint(None, 'auth_user_groups', type_='foreignkey')
    # ### end Alembic commands ###
