"""init

Revision ID: ef7c1b8061fc
Revises: 
Create Date: 2023-02-26 00:33:36.887583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7c1b8061fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_auth_group_id'), 'auth_group', ['id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_groups_id'), 'auth_user_groups', ['id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=95), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=45), nullable=True),
    sa.Column('keywords', sa.String(length=50), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('explored', sa.Boolean(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('fail', sa.Boolean(), nullable=True),
    sa.Column('login', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_explored'), 'link', ['explored'], unique=False)
    op.create_index(op.f('ix_link_id'), 'link', ['id'], unique=False)
    op.create_index(op.f('ix_link_link'), 'link', ['link'], unique=True)
    op.create_index(op.f('ix_link_running'), 'link', ['running'], unique=False)
    op.create_index(op.f('ix_link_verify'), 'link', ['verify'], unique=False)
    op.create_table('link_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_link', sa.Integer(), nullable=True),
    sa.Column('id_href', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_link', 'id_href', name='unique_component_commit')
    )
    op.create_index(op.f('ix_link_connection_id'), 'link_connection', ['id'], unique=False)
    op.create_index(op.f('ix_link_connection_id_href'), 'link_connection', ['id_href'], unique=False)
    op.create_index(op.f('ix_link_connection_id_link'), 'link_connection', ['id_link'], unique=False)
    op.create_table('subpage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('fail', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subpage_id'), 'subpage', ['id'], unique=False)
    op.create_index(op.f('ix_subpage_link'), 'subpage', ['link'], unique=True)
    op.create_index(op.f('ix_subpage_running'), 'subpage', ['running'], unique=False)
    op.create_index(op.f('ix_subpage_verify'), 'subpage', ['verify'], unique=False)
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('fail', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_id'), 'url', ['id'], unique=False)
    op.create_index(op.f('ix_url_link'), 'url', ['link'], unique=True)
    op.create_index(op.f('ix_url_running'), 'url', ['running'], unique=False)
    op.create_index(op.f('ix_url_verify'), 'url', ['verify'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_verify'), table_name='url')
    op.drop_index(op.f('ix_url_running'), table_name='url')
    op.drop_index(op.f('ix_url_link'), table_name='url')
    op.drop_index(op.f('ix_url_id'), table_name='url')
    op.drop_table('url')
    op.drop_index(op.f('ix_subpage_verify'), table_name='subpage')
    op.drop_index(op.f('ix_subpage_running'), table_name='subpage')
    op.drop_index(op.f('ix_subpage_link'), table_name='subpage')
    op.drop_index(op.f('ix_subpage_id'), table_name='subpage')
    op.drop_table('subpage')
    op.drop_index(op.f('ix_link_connection_id_link'), table_name='link_connection')
    op.drop_index(op.f('ix_link_connection_id_href'), table_name='link_connection')
    op.drop_index(op.f('ix_link_connection_id'), table_name='link_connection')
    op.drop_table('link_connection')
    op.drop_index(op.f('ix_link_verify'), table_name='link')
    op.drop_index(op.f('ix_link_running'), table_name='link')
    op.drop_index(op.f('ix_link_link'), table_name='link')
    op.drop_index(op.f('ix_link_id'), table_name='link')
    op.drop_index(op.f('ix_link_explored'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_auth_user_groups_id'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index(op.f('ix_auth_group_id'), table_name='auth_group')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
